### ISSUE TITLE
Create zombie horde

### ISSUE THREAD

**Issue by btzr-io** [UnityNoobs/recess-zombie-escape-game#23]

**Comment by btzr-io** [comment]
Do we need more work on this?

**Comment by Bradels** [comment]
Maybe?
The basic logic is there.
I vote we close this issue and create another one if we need.

**Comment by btzr-io** [comment]
@Bradels Please reference the issue you are closing on the PR 
https://help.github.com/articles/closing-issues-using-keywords/
