### ISSUE TITLE
Create player

### ISSUE THREAD

**Issue by btzr-io** [UnityNoobs/recess-zombie-escape-game#29]
Create basic player prefab:

- [x] Add platform behavior
- [x] Attack system #39 #54 #43

**Comment by kingcrime** [comment]
Need help on sprite image for player, i will work on the program

**Comment by btzr-io** [comment]
I don't really know how coop controls work on pc, but if we could support gamepads that would be awesome

**Comment by kingcrime** [comment]
i already update it on branch...just like retro time...keypad control is for second player...

**Comment by btzr-io** [comment]
I'll help @kingcrime when I'm back from school :v:

**Comment by Bradels** [comment]
Can we add Mario style jumping?
https://www.youtube.com/watch?v=7KiK0Aqtmzc

**Comment by kingcrime** [comment]
sure..i will modify it..

**Comment by btzr-io** [comment]
@kingcrime your branch still has conflicts, anyway I modify your player script, I'll push the changes to master...

**Comment by btzr-io** [comment]
@kingcrime @Brades I pushed the platform behavior script, I try to follow the video about the mario jump stye but didn't work really well, anyway feel free to rewrite the jump code :v: and assign yourself to https://github.com/UnityNoobs/recess-zombie-escape-game/issues/38#issuecomment-437268593

**Comment by btzr-io** [comment]
@kingcrime @Brades I pushed the platform behavior script, I try to follow the video about the mario jump stye but didn't work really well, anyway feel free to rewrite the jump code :v: and assign yourself to https://github.com/UnityNoobs/recess-zombie-escape-game/issues/38#issuecomment-437268593

**Comment by btzr-io** [comment]
I'll close this, we need improvements but they should be a different task
