### ISSUE TITLE
Add attack system for player

### ISSUE THREAD

**Issue by btzr-io** [UnityNoobs/recess-zombie-escape-game#39]
The player will be using a weapon that throw a specific type of projectile.
- You will need instanciate the bullet from https://github.com/UnityNoobs/recess-zombie-escape-game/issues/42
- Implement reloading system #43 

> :information_source:  **Note:** It needs to be to be flexible, easy to extend and use.

**Comment by Bradels** [comment]
The movement script and the attack script are in the same scripted.
We separate the systems for greater future flexibility.

**Comment by Bradels** [comment]
This is strongly related to  #55
I can include the "reload" and ammo count etc in Weapon Class.

**Comment by btzr-io** [comment]
This is now implemented, but needs improvements
