### ISSUE TITLE
Create a memory pool manager

### ISSUE THREAD

**Issue by btzr-io** [UnityNoobs/recess-zombie-escape-game#49]
We need a memory pool script to instantiate enemies, projectiles and other prefabs.
Just write the script and functions for generic purposes, we will implement it later.

**Comment by Bradels** [comment]
I'm going to be implementing a generic Object Pool for use in the game.
I'll also write up a "how to use", do we have a place for such documentation?

**Comment by Bradels** [comment]
Largely implemented from a tutorial based off this repo.
https://github.com/Rfrixy/Generic-Unity-Object-Pooler
